#pragma once

#include "game_state.h"

// Unique ID
#define BASIC_PLANT_ID 0xA0

// Picture filename
#define BASIC_PLANT_PICTURE "basic_plant.png"

// Size bits
#define BASIC_PLANT_SIZE_BITS_PADDING (ID_BITS_COUNT)
#define BASIC_PLANT_SIZE_BITS_COUNT (4LL)
#define BASIC_PLANT_SIZE_BITS (0xFLL << BASIC_PLANT_SIZE_BITS_PADDING)

#define BASIC_PLANT_SIZE_0 (0LL << BASIC_PLANT_SIZE_BITS_PADDING)
#define BASIC_PLANT_SIZE_1 (1LL << BASIC_PLANT_SIZE_BITS_PADDING)
#define BASIC_PLANT_SIZE_2 (2LL << BASIC_PLANT_SIZE_BITS_PADDING)
#define BASIC_PLANT_SIZE_3 (3LL << BASIC_PLANT_SIZE_BITS_PADDING)
#define BASIC_PLANT_SIZE_4 (4LL << BASIC_PLANT_SIZE_BITS_PADDING)

// Color bits
#define BASIC_PLANT_COLOR_BITS_PADDING (BASIC_PLANT_SIZE_BITS_PADDING + BASIC_PLANT_SIZE_BITS_COUNT) 
#define BASIC_PLANT_COLOR_BITS_COUNT (24LL)
#define BASIC_PLANT_COLOR_BITS (0xFFFFFFLL << BASIC_PLANT_COLOR_BITS_PADDING)

// Age bits
#define BASIC_PLANT_AGE_BITS_PADDING (BASIC_PLANT_COLOR_BITS_PADDING + BASIC_PLANT_COLOR_BITS_COUNT) 
#define BASIC_PLANT_AGE_BITS_COUNT (5LL)
#define BASIC_PLANT_AGE_BITS (0x1FLL << BASIC_PLANT_AGE_BITS_PADDING)

#define BASIC_PLANT_AGE_MAX (BASIC_PLANT_AGE_BITS - (0x1LL << BASIC_PLANT_AGE_BITS_PADDING))

// Public functions
void basic_plant_live(game_state* game, size_t game_board_index);
